version: '3.7'
volumes:
  data:
services:
  api:
    build: .
    container_name: ze_delivery_api
    restart: unless-stopped
    ports:
     - "5000:5000" # http
    #  - "443:443" # https
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ze_admin
      MONGO_INITDB_ROOT_PASSWORD: 10YKs8yyHIV0TxFI
      MONGO_INITDB_DATABASE: ze_delivery
      MONGO_INITDB_USERNAME: ze_user
      MONGO_INITDB_PASSWORD: hES6m2EXdjKqVkRf
    volumes:
      - /data/db
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
    - "8001:8080"
    volumes:
      - ./docs/swagger.yml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml
    links:
      - api
      - db
