swagger: "2.0"
info:
  version: "1.0"
  title: Zé Delivery API
  contact:
    email: "thiagoluiz.dev@gmail.com"

basePath: /v1/

consumes:
- application/json
produces:
- application/json
schemes:
- http

host: localhost:5001
paths:
